version = 0.1
[default.deploy.parameters]
stack_name = "mentoria-sysmap"
resolve_s3 = true
s3_prefix = "mentoria-sysmap"
region = "sa-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
